project_id: coastal-well-455704-a7
location: us-central1
gemini_model_name: gemini-2.5-flash-preview-05-20
embedding_model_name: text-embedding-004
image_generation_model_name: imagen-3.0-fast-generate-002
database: (default)
collection: poses
test_collection: test-poses
top_k: "3"
